telerik/kendo-angular-messages

bin/kendo-translate.js
package.json

Fixed in xlf-translate 2.0
Closes #14

fix: error with interpolations

---

messages/numerictextbox/numerictextbox.ar.yml

numerictextbox.ar.yml  arabic messages

---

messages/datepicker/datepicker.ar.yml

date picker Arabic messages

---

messages/dateinput/dateinput.ar.yml

Arabic Messages

---

messages/upload/upload.fr-BE.yml
messages/upload/upload.fr-CA.yml
messages/upload/upload.fr-CD.yml
messages/upload/upload.fr-CH.yml
messages/upload/upload.fr-CI.yml
messages/upload/upload.fr-FR.yml
messages/upload/upload.fr-HT.yml
messages/upload/upload.fr-LU.yml
messages/upload/upload.fr-MA.yml
messages/upload/upload.fr-MC.yml
messages/upload/upload.fr-ML.yml
messages/upload/upload.fr-SN.yml

Some french translations where missing for upload component.
Hope this PR will help.

Added french translations for upload component

---

.gitignore
messages/calendar/calendar.ru-RU.yml
messages/calendar/dateinput.ru-RU.yml
messages/dateinput/dateinput.ru-RU.yml
messages/datepicker/datepicker.ru-RU.yml
messages/grid/grid.ru-RU.yml
messages/numerictextbox/numerictextbox.ru-RU.yml
messages/slider/slider.ru-RU.yml
messages/upload/upload.ru-RU.yml

fix: ru-RU localization

---

messages/dateinput/dateinput.sv-SE.yml
messages/numerictextbox/numerictextbox.sv-SE.yml
messages/slider/slider.sv-SE.yml

Increase, Decrease value was in another language than Swedish

Swedish text fix

---

messages/grid/grid.sv-SE.yml

I am using this component myself and i would really appreciate if these missing translations could get merged in :)

Added missing swedish translations for grid

---

messages/grid/grid.de-AT.yml
messages/grid/grid.de-CH.yml
messages/grid/grid.de-DE.yml
messages/grid/grid.de-LI.yml

Applied suggestions from https://github.com/telerik/kendo-angular-messages/issues/65
Thanks @m-reiseder! Please, review the changes and sign the [Contributor License Agreement](https://goo.gl/forms/dXc1RaE8le6rVZ0h1) so we can publish an updated version.

 fix: Grid messages in German

---

messages/dropdowns/dropdowns.bg-BG.yml
messages/dropdowns/dropdowns.en-GB.yml
messages/dropdowns/dropdowns.en-US.yml

see telerik/kendo-angular-messages#68

feat(dropdowns): add dropdowns messages for en-GB, en-US and bg-BG

---

.travis.yml

https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

chore: migrate away from container build infra

---

messages/timepicker/timepicker.fr-BE.yml
messages/timepicker/timepicker.fr-CA.yml
messages/timepicker/timepicker.fr-CD.yml
messages/timepicker/timepicker.fr-CH.yml
messages/timepicker/timepicker.fr-CI.yml
messages/timepicker/timepicker.fr-CM.yml
messages/timepicker/timepicker.fr-FR.yml
messages/timepicker/timepicker.fr-HT.yml
messages/timepicker/timepicker.fr-LU.yml
messages/timepicker/timepicker.fr-MA.yml
messages/timepicker/timepicker.fr-MC.yml
messages/timepicker/timepicker.fr-ML.yml
messages/timepicker/timepicker.fr-SN.yml

Fix French translations of 'Set' button in TimePicker

Fix French translations of TimePicker

---

messages/datepicker/datepicker.de-DE.yml
messages/dropdowns/dropdowns.de-DE.yml
messages/grid/grid.de-DE.yml
messages/slider/slider.de-DE.yml
messages/switch/switch.de-DE.yml
messages/timepicker/timepicker.de-DE.yml
messages/upload/upload.de-DE.yml

fix: German translations

---

messages/grid/grid.ru-RU.yml

Update RU grid localizations

---

messages/scheduler/scheduler.fr-BE.yml
messages/scheduler/scheduler.fr-CA.yml
messages/scheduler/scheduler.fr-CD.yml
messages/scheduler/scheduler.fr-CH.yml
messages/scheduler/scheduler.fr-CI.yml
messages/scheduler/scheduler.fr-CM.yml
messages/scheduler/scheduler.fr-FR.yml
messages/scheduler/scheduler.fr-HT.yml
messages/scheduler/scheduler.fr-LU.yml
messages/scheduler/scheduler.fr-MA.yml
messages/scheduler/scheduler.fr-MC.yml
messages/scheduler/scheduler.fr-ML.yml
messages/scheduler/scheduler.fr-SN.yml

Add missing translations in french scheduler.

Updating Fr Scheduler messages

---

messages/scheduler/scheduler.fr-BE.yml
messages/scheduler/scheduler.fr-CA.yml
messages/scheduler/scheduler.fr-CD.yml
messages/scheduler/scheduler.fr-CH.yml
messages/scheduler/scheduler.fr-CI.yml
messages/scheduler/scheduler.fr-CM.yml
messages/scheduler/scheduler.fr-FR.yml
messages/scheduler/scheduler.fr-HT.yml
messages/scheduler/scheduler.fr-LU.yml
messages/scheduler/scheduler.fr-MA.yml
messages/scheduler/scheduler.fr-MC.yml
messages/scheduler/scheduler.fr-ML.yml
messages/scheduler/scheduler.fr-SN.yml

Add missing French translations for scheduler

French translations for scheduler

---

messages/scheduler/scheduler.fr-BE.yml
messages/scheduler/scheduler.fr-CA.yml
messages/scheduler/scheduler.fr-CD.yml
messages/scheduler/scheduler.fr-CH.yml
messages/scheduler/scheduler.fr-CI.yml
messages/scheduler/scheduler.fr-CM.yml
messages/scheduler/scheduler.fr-FR.yml
messages/scheduler/scheduler.fr-HT.yml
messages/scheduler/scheduler.fr-LU.yml
messages/scheduler/scheduler.fr-MA.yml
messages/scheduler/scheduler.fr-MC.yml
messages/scheduler/scheduler.fr-ML.yml
messages/scheduler/scheduler.fr-SN.yml

Fix some french scheduler translations

Fix some french scheduler translations

---

gulpfile.js
package-lock.json
package.json

chore: update to Gulp 4

---

messages/textbox/textbox.es-ES.yml

Add pending es-ES translation.

Add pending es-ES translation.

---

messages/grid/grid.fr-BE.yml
messages/grid/grid.fr-CA.yml
messages/grid/grid.fr-CD.yml
messages/grid/grid.fr-CH.yml
messages/grid/grid.fr-CI.yml
messages/grid/grid.fr-CM.yml
messages/grid/grid.fr-FR.yml
messages/grid/grid.fr-HT.yml
messages/grid/grid.fr-LU.yml
messages/grid/grid.fr-MA.yml
messages/grid/grid.fr-MC.yml
messages/grid/grid.fr-ML.yml
messages/grid/grid.fr-SN.yml
messages/treelist/treelist.fr-BE.yml
messages/treelist/treelist.fr-CA.yml
messages/treelist/treelist.fr-CD.yml
messages/treelist/treelist.fr-CH.yml
messages/treelist/treelist.fr-CI.yml
messages/treelist/treelist.fr-CM.yml
messages/treelist/treelist.fr-FR.yml
messages/treelist/treelist.fr-HT.yml
messages/treelist/treelist.fr-LU.yml
messages/treelist/treelist.fr-MA.yml
messages/treelist/treelist.fr-MC.yml
messages/treelist/treelist.fr-ML.yml
messages/treelist/treelist.fr-SN.yml

chore: update Less than filter operator french translations

---

package.json
tools/seed-messages.sh

Adds a script to copy initial messages for new components.

chore: add seed-messages script

---

package-lock.json
package.json

Closes #166 via https://github.com/tsvetomir/xlf-translate/pull/10

fix: do not add empty targets

---

messages/calendar/calendar.sv-SE.yml

Translated prevButtonTitle & nextButtonTitle to swedish

Translated calendar.sv-SE.yml

---

messages/datepicker/datepicker.sv-SE.yml

Translated toggle, prevButtonTitle & nextButtonTitle

Translate datepicker.sv-SE.yml

---

messages/toolbar/toolbar.fr-BE.yml
messages/toolbar/toolbar.fr-CA.yml
messages/toolbar/toolbar.fr-CD.yml
messages/toolbar/toolbar.fr-CH.yml
messages/toolbar/toolbar.fr-CI.yml
messages/toolbar/toolbar.fr-CM.yml
messages/toolbar/toolbar.fr-FR.yml
messages/toolbar/toolbar.fr-HT.yml
messages/toolbar/toolbar.fr-LU.yml
messages/toolbar/toolbar.fr-MA.yml
messages/toolbar/toolbar.fr-MC.yml
messages/toolbar/toolbar.fr-ML.yml
messages/toolbar/toolbar.fr-SN.yml

Fix for the french translation of the "more tools" button in a responsive ToolBar

French translation fix

---

LICENSE.md
NOTICE.txt

docs: update notice && change year 2022

---

messages/calendar/calendar.it-IT.yml
messages/colorgradient/colorgradient.it-IT.yml
messages/colorpicker/colorpicker.it-IT.yml
messages/editor/editor.it-IT.yml
messages/flatcolorpicker/flatcolorpicker.it-IT.yml
messages/gantt/gantt.it-IT.yml
messages/grid/grid.it-CH.yml
messages/grid/grid.it-IT.yml
messages/pager/pager.it-IT.yml
messages/pivotgrid/pivotgrid.it-IT.yml
messages/scheduler/scheduler.it-IT.yml
messages/signature/signature.it-IT.yml
messages/tabstrip/tabstrip.it-IT.yml
messages/timepicker/timepicker.it-IT.yml
messages/treelist/treelist.it-CH.yml
messages/treelist/treelist.it-IT.yml

Updated it-IT translation messages for:
- Calendar
- ColorGradient
- ColorPicker
- Editor
- FlatColorPicker
- Gantt
- Grid
- Pager
- PivotGrid
- Scheduler
- Signature
- TabStrip
- TimePicker
- TreeList

Update it-IT messages

---

.github/workflows/cd.yml
.github/workflows/publish.yml

Ref https://github.com/telerik/devtools-okrs/issues/220

Read secrets from Akeyless

---

messages/dateinput/dateinput.es-ES.yml
messages/dropdowns/dropdowns.es-ES.yml
messages/grid/grid.es-ES.yml
messages/spreadsheet/spreadsheet.es-ES.yml
messages/treelist/treelist.es-ES.yml

feat(i18n): Add Spanish translations for Kendo UI Spreadsheet

feat(spreadsheet, treelist, grid, dateinputs, dropdowns): update ES translations
